import { FIXTURES, NORMAL_IMPACT_MS, ProductRendererSession, type Scene, type Variant } from './fixture';import { ProductAudioSession } from './productAudioSession';
declare global{interface Window{__R5B_READY__?:boolean;__R5B_TEST__?:typeof api;render_game_to_text?:()=>string;advanceTime?:(ms:number)=>void;}}
await window.__R5B_TEST__?.dispose('hmr-replace');const need=<T extends Element>(s:string)=>{const e=document.querySelector<T>(s);if(!e)throw new Error(`Missing ${s}`);return e};const host=need<HTMLElement>('#canvas-host'),status=need<HTMLElement>('#status'),time=need<HTMLOutputElement>('#time'),title=need<HTMLElement>('#scene-title'),technical=need<HTMLElement>('#technical'),form=need<HTMLFormElement>('#verdict'),verdictOut=need<HTMLOutputElement>('#verdict-output');
const instanceId=Math.round(performance.timeOrigin+performance.now());const timers=new Set<number>(),listeners:Array<()=>void>=[];let ready=false,disposed=false,disposing=false,enabled=true,lastVariant:Variant='A',playCount=0,error:string|null=null;const renderer=new ProductRendererSession(host,update),audio=new ProductAudioSession(update);function listen(target:EventTarget,type:string,handler:EventListener){target.addEventListener(type,handler);listeners.push(()=>target.removeEventListener(type,handler))}
const clearTimers=()=>{for(const id of timers)clearTimeout(id);timers.clear()};const later=(fn:()=>void,ms:number)=>{const id=setTimeout(()=>{timers.delete(id);fn();update()},ms);timers.add(id)};const activation=(scene:Scene)=>FIXTURES[scene].activation;const beats=(scene:Scene,reduced:boolean)=>scene==='normal'?[NORMAL_IMPACT_MS]:[...(reduced?FIXTURES.plans.reduced:FIXTURES.plans.full).beatStartsMs];
async function playEvent(scene:Scene,variant:Variant,reduced=false,deterministic=false){if(disposed||!enabled)return;clearTimers();lastVariant=variant;renderer.play(scene,reduced,deterministic);await audio.play(scene,variant,reduced,activation(scene),beats(scene,reduced));playCount++;update();}
async function playPair(variant:Variant){await playEvent('normal',variant,false);later(()=>void playEvent('chain',variant,false).catch(fail),950)}function stop(){clearTimers();audio.stopReusable();renderer.stop();update()}async function restart(){stop();await playPair(lastVariant)}function toggle(){enabled=!enabled;if(enabled)audio.enable();else{audio.disable();clearTimers();renderer.stop()}need<HTMLButtonElement>('#disable').textContent=enabled?'禁用声音':'重新启用';update()}
function fail(value:unknown){error=value instanceof Error?value.message:String(value);stop();console.error(value)}function update(){const r=renderer.state(),a=audio.state();time.value=`${Math.round(r.elapsedMs)} ms`;title.textContent=`真实 Core · ${r.scene==='chain'?'row-39 连锁':'正常 Bomb'}`;status.textContent=disposed?'实例已终止':error?`已停止：${error}`:ready?'生产 Renderer / AudioEngine 证据页就绪':'正在准备生产 Renderer…';technical.textContent=`Instance ${instanceId} · Canvas ${r.canvasCount} · Context ${a.liveContexts} · Source ${a.eventSources} · Timer ${timers.size}`;document.body.dataset.ready=String(ready&&!disposed&&!disposing)}
listen(document,'click',((e:MouseEvent)=>{const button=(e.target as Element).closest<HTMLButtonElement>('button');if(!button)return;const variant=button.dataset.pair as Variant|undefined;if(variant)void playPair(variant).catch(fail);else if(button.id==='stop')stop();else if(button.id==='restart')void restart().catch(fail);else if(button.id==='disable')toggle();else if(button.id==='reduced')void playEvent('chain','A',true,true).catch(fail)}) as EventListener);listen(form,'submit',((e:SubmitEvent)=>{e.preventDefault();const value=new FormData(form).get('verdict')??'reject';verdictOut.value=`本页临时记录：${value}；未持久化，也不构成接受。`}) as EventListener);
function state(){const selected=document.querySelector<HTMLInputElement>('input[name=verdict]:checked');return{instanceId,ready:ready&&!disposed&&!disposing,disposed,disposing,enabled,playCount,verdict:selected?.value??'reject',pendingTimers:timers.size,listenerCount:listeners.length,renderer:renderer.state(),audio:audio.state(),fixture:renderer.fixtureState(),canvasCount:document.querySelectorAll('canvas').length,domCellCount:document.querySelectorAll('[data-cell]').length,qaGlobals:window.__R5B_TEST__===api,error};}
let disposePromise:Promise<void>|null=null;function dispose(_reason='destroy'){if(disposePromise)return disposePromise;disposePromise=(async()=>{disposing=true;ready=false;clearTimers();for(const remove of listeners.splice(0))remove();renderer.dispose();await audio.dispose();disposed=true;disposing=false;if(window.__R5B_TEST__===api){delete window.__R5B_TEST__;delete window.__R5B_READY__;delete window.render_game_to_text;delete window.advanceTime}update()})();return disposePromise}
const api=Object.freeze({getState:state,prime:(v:Variant='A')=>audio.prime(v),playEvent,playPair,stop,restart,disable:()=>{if(enabled)toggle()},enable:()=>{if(!enabled)toggle()},dispose,hotDispose:()=>dispose('vite-hmr')});window.__R5B_TEST__=api;window.render_game_to_text=()=>JSON.stringify(state());window.advanceTime=ms=>renderer.advance(Math.max(0,ms));listen(window,'pagehide',(()=>void dispose('pagehide')) as EventListener);import.meta.hot?.dispose(()=>dispose('vite-hmr'));
renderer.init().then(()=>{if(disposed)return;ready=true;window.__R5B_READY__=true;update()}).catch(fail);
