import { BOARD_HEIGHT, BOARD_WIDTH, LINE_CLEAR_DELAY_TICKS, VISIBLE_START_ROW, createBoard, createInitialState, dispatch, setCell, type GameEvent, type GameState } from '../../../../src/game/core';
import { mutationChainPresentationPlan } from '../../../../src/animation/mutationChainTimeline';
import { MUTATION_VFX_TOKENS } from '../../../../src/design/mutationTokens';
import { TetrisRenderer } from '../../../../src/game/render/TetrisRenderer';
export type Variant='A'|'B'|'C'; export type Scene='normal'|'chain';
type Bomb=Extract<GameEvent,{type:'mutation-activated';item:'bomb'}>; type Chain=Extract<Bomb,{bombOutcome:'chain-clear'}>;
function ok(value:unknown,message:string):asserts value{if(!value)throw new Error(message)}
function commit(state:GameState){const started=dispatch(state,{type:'hard-drop'});let settled=started;for(let i=0;i<LINE_CLEAR_DELAY_TICKS;i++)settled=dispatch(settled.state,{type:'tick'});const activation=settled.events.find((e):e is Bomb=>e.type==='mutation-activated'&&e.item==='bomb');ok(activation,'Core emitted no Bomb activation.');return{initialState:state,hardDropState:started.state,hardDropEvents:started.events,committedState:settled.state,committedEvents:settled.events,activation};}
function base(){return dispatch(createInitialState(0x37b05b,'sprint'),{type:'start'}).state;}
export function createFixtures(){let board=createBoard();for(let x=0;x<8;x++)board=setCell(board,x,39,'J');const common={...base(),board,active:{type:'O',rotation:0,x:8,y:38} as const,score:0};
 const normal=commit({...common,mutationActiveCarrier:{id:9,item:'bomb'},mutationCarriers:[],mutationNextCarrierId:10});
 const chain=commit({...common,board:setCell(board,0,38,'L'),mutationActiveCarrier:{id:1,item:'bomb'},mutationCarriers:[{id:2,item:'bomb',cells:[{x:0,y:38},{x:0,y:39}]}],mutationNextCarrierId:3});
 ok(normal.activation.bombOutcome==='blast'&&normal.activation.participatingBombCount===1,'Normal Core fixture drifted.');ok(chain.activation.bombOutcome==='chain-clear','Chain Core fixture drifted.');const c=chain.activation as Chain;ok(JSON.stringify(c.chainTriggerRows)==='[39]'&&c.participatingBombCount===2,'Row-39 Core chain drifted.');
 return{normal,chain,plans:{full:mutationChainPresentationPlan(c.chainTriggerRows,false),reduced:mutationChainPresentationPlan(c.chainTriggerRows,true)}};}
export const FIXTURES=createFixtures(); export const NORMAL_IMPACT_MS=MUTATION_VFX_TOKENS.bomb.animation.enterMs+MUTATION_VFX_TOKENS.bomb.animation.pulseMs;
export class ProductRendererSession{private renderer:TetrisRenderer|null=null;private scene:Scene|null=null;private elapsed=0;private callback=false;private disposed=false;constructor(private host:HTMLElement,private changed:()=>void=()=>{}){}
 async init(){ok(!this.disposed,'Renderer disposed.');const r=new TetrisRenderer();r.setOptions({visualTheme:'deep-tide',reducedMotion:false,modeSwitch:false});await r.init(this.host);if(this.disposed){r.destroy();return}this.renderer=r;r.render(FIXTURES.normal.hardDropState,[{type:'restarted'}],0);ok(this.host.querySelectorAll('canvas').length===1,'Renderer must own one Canvas.');this.changed();}
 play(scene:Scene,reduced=false,deterministic=false){const renderer=this.renderer;ok(renderer&&!this.disposed,'Renderer unavailable.');this.stop();this.scene=scene;this.elapsed=0;const f=FIXTURES[scene];renderer.setOptions({reducedMotion:reduced});renderer.render(f.committedState,f.committedEvents,0);if(!deterministic){this.callback=true;renderer.setFrameCallback(d=>this.advance(Math.min(d,100)));}this.changed();}
 advance(ms:number){if(!this.renderer||!this.scene)return;let rest=Math.max(0,ms);while(rest>0){const d=Math.min(rest,1000/60);rest-=d;this.elapsed+=d;this.renderer.render(FIXTURES[this.scene].committedState,[],d);}this.changed();}
 stop(){this.renderer?.setFrameCallback(()=>{});this.callback=false;this.scene=null;this.elapsed=0;if(this.renderer)this.renderer.render(FIXTURES.normal.hardDropState,[{type:'restarted'}],0);this.changed();}
 state(){const snap=this.renderer?.getSnapshot();return{ready:!!this.renderer&&!this.disposed,disposed:this.disposed,scene:this.scene,elapsedMs:this.elapsed,frameCallbacks:this.callback?1:0,tickerOwners:this.renderer?1:0,rendererOwners:this.renderer?1:0,canvasCount:this.host.querySelectorAll('canvas').length,particles:snap?.mutationActiveParticleCount??0};}
 fixtureState(){const c=FIXTURES.chain.activation as Chain;return{normalOutcome:FIXTURES.normal.activation.bombOutcome,normalParticipants:FIXTURES.normal.activation.participatingBombCount,chainOutcome:c.bombOutcome,chainParticipants:c.participatingBombCount,chainTriggerRows:[...c.chainTriggerRows],fullBeatStartsMs:[...FIXTURES.plans.full.beatStartsMs],reducedBeatStartsMs:[...FIXTURES.plans.reduced.beatStartsMs],fullDurationMs:FIXTURES.plans.full.durationMs,reducedDurationMs:FIXTURES.plans.reduced.durationMs,boardWidth:BOARD_WIDTH,boardHeight:BOARD_HEIGHT,visibleStartRow:VISIBLE_START_ROW,normalImpactMs:NORMAL_IMPACT_MS};}
 dispose(){if(this.disposed)return;this.disposed=true;this.stop();this.renderer?.destroy();this.renderer=null;this.host.replaceChildren();this.changed();}}
