import type { GameEvent } from '../../../../src/game/core';import { createBrowserPlatform } from '../../../../src/platform/browserPlatform';import { AudioEngine, type BombStemVariant } from '../../../../src/game/audio/AudioEngine';import { fetchAcceptedAudioAsset } from '../../../../src/game/audio/acceptedPlayback';import type { Scene,Variant } from './fixture';
type SourceAudit={id:number;started:boolean;startAt:number|null;stopCalls:number;disconnected:boolean;connections:number};type BufferAudit={id:number;channels:number;frames:number;sampleRate:number;buffer:AudioBuffer};
type ContextAudit={id:number;context:AudioContext;closed:boolean;closePromise:Promise<void>|null;buffers:BufferAudit[];sources:SourceAudit[]};
export type EventAudit={scene:Scene;variant:Variant;reducedMotion:boolean;beatStartsMs:number[];contextId:number;bufferId:number;sourceId:number};
const finite=(samples:Float32Array,firstBeatMs:number)=>{let max=0,preBeatMaxAbs=0,firstNonZeroFrame=-1;const firstBeatFrame=firstBeatMs*48;for(let i=0;i<samples.length;i++){const value=samples[i]!;if(!Number.isFinite(value))return{finite:false,maxAbs:Infinity,preBeatMaxAbs:Infinity,firstNonZeroFrame};const abs=Math.abs(value);max=Math.max(max,abs);if(i<firstBeatFrame)preBeatMaxAbs=Math.max(preBeatMaxAbs,abs);if(firstNonZeroFrame<0&&abs>0)firstNonZeroFrame=i;}return{finite:true,maxAbs:max,preBeatMaxAbs,firstNonZeroFrame};};
export class ProductAudioSession{private engine:AudioEngine|null=null;private variant:Variant|null=null;private enabled=true;private disposed=false;private contexts:ContextAudit[]=[];private events:EventAudit[]=[];constructor(private changed:()=>void=()=>{}){}
 private makeContext(){const context=new AudioContext({sampleRate:48000});const audit:ContextAudit={id:this.contexts.length+1,context,closed:false,closePromise:null,buffers:[],sources:[]};this.contexts.push(audit);const makeBuffer=context.createBuffer.bind(context),makeSource=context.createBufferSource.bind(context),close=context.close.bind(context);
  context.createBuffer=((channels:number,frames:number,rate:number)=>{const buffer=makeBuffer(channels,frames,rate);audit.buffers.push({id:audit.buffers.length+1,channels,frames,sampleRate:rate,buffer});return buffer;}) as typeof context.createBuffer;
  context.createBufferSource=(()=>{const source=makeSource(),record:SourceAudit={id:audit.sources.length+1,started:false,startAt:null,stopCalls:0,disconnected:false,connections:0};audit.sources.push(record);const start=source.start.bind(source),stop=source.stop.bind(source),connect=source.connect.bind(source),disconnect=source.disconnect.bind(source);source.start=((at=0,...rest:number[])=>{record.started=true;record.startAt=at;return start(at,...rest as [number,number]);}) as typeof source.start;source.stop=((at=0)=>{record.stopCalls++;return stop(at);}) as typeof source.stop;source.connect=((target:AudioNode)=>{record.connections++;return connect(target);}) as typeof source.connect;source.disconnect=(()=>{record.disconnected=true;return disconnect();}) as typeof source.disconnect;return source;}) as typeof context.createBufferSource;
  context.close=(()=>{const pending=close().then(()=>{audit.closed=true;this.changed();});audit.closePromise=pending;return pending;}) as typeof context.close;this.changed();return context;}
 private async select(variant:Variant){if(this.disposed)throw new Error('Audio owner disposed.');if(this.engine&&this.variant===variant)return;if(this.engine){this.engine.destroy();await Promise.all(this.contexts.map(c=>c.closePromise).filter(Boolean));}this.variant=variant;const platform=createBrowserPlatform({window,document,audioContextFactory:()=>this.makeContext()});this.engine=new AudioEngine(platform,fetchAcceptedAudioAsset,{forceBombStemVariantForTest:variant as BombStemVariant});this.engine.setEnabled(this.enabled);this.engine.setVolume(1);}
 async prime(variant:Variant){await this.select(variant);await this.engine?.prime();this.changed();}
 async play(scene:Scene,variant:Variant,reduced:boolean,event:GameEvent,beats:readonly number[]){await this.prime(variant);if(!this.engine||!this.enabled)return;this.stopReusable('switch');this.engine.setReducedMotion(reduced);const context=this.contexts.at(-1)!;const b=context.buffers.length,s=context.sources.length;this.engine.play([event]);if(context.buffers.length!==b+1||context.sources.length!==s+1)throw new Error('Bomb event did not create exactly one buffer/source.');this.events.push({scene,variant,reducedMotion:reduced,beatStartsMs:[...beats],contextId:context.id,bufferId:context.buffers.at(-1)!.id,sourceId:context.sources.at(-1)!.id});this.changed();}
 stopReusable(_reason='stop'){this.engine?.play([{type:'restarted'}]);this.changed();} disable(){this.enabled=false;this.engine?.setEnabled(false);this.changed();} enable(){this.enabled=true;this.engine?.setEnabled(true);this.changed();}
 state(){const live=this.contexts.filter(c=>!c.closed),current=this.contexts.at(-1),eventDetails=this.events.map(event=>{const context=this.contexts.find(c=>c.id===event.contextId)??current;const buffer=context?.buffers.find(b=>b.id===event.bufferId),source=context?.sources.find(s=>s.id===event.sourceId),signal=buffer?finite(buffer.buffer.getChannelData(0),event.beatStartsMs[0]??0):{finite:false,maxAbs:Infinity,preBeatMaxAbs:Infinity,firstNonZeroFrame:-1};return{...event,channels:buffer?.channels,frames:buffer?.frames,sampleRate:buffer?.sampleRate,...signal,sourceStarted:source?.started,sourceDisconnected:source?.disconnected,sourceConnections:source?.connections};});return{disposed:this.disposed,variant:this.variant,enabled:this.enabled,contextsCreated:this.contexts.length,liveContexts:live.length,contextState:current?.context.state??'none',eventSources:this.contexts.flatMap(c=>c.sources).filter(s=>!s.disconnected).length,eventBuffers:this.contexts.reduce((n,c)=>n+c.buffers.length,0),events:eventDetails};}
 async dispose(){if(this.disposed)return;this.disposed=true;this.engine?.destroy();this.engine=null;await Promise.all(this.contexts.map(c=>c.closePromise).filter((p):p is Promise<void>=>!!p));this.changed();}}
