import type { PuzzleDefinition } from './puzzles';

const INTRO_01: PuzzleDefinition = Object.freeze({
  id: 't3r-shaft-01',
  name: '补行',
  difficulty: 1,
  targetRows: 3,
  seed: 1212,
  setup: Object.freeze({
    seed: 2080886771,
    placements: Object.freeze([
      Object.freeze({ type: 'J', rotation: 0, x: 4 }),
      Object.freeze({ type: 'Z', rotation: 0, x: 6 }),
      Object.freeze({ type: 'T', rotation: 2, x: 4 }),
      Object.freeze({ type: 'O', rotation: 0, x: 1 }),
      Object.freeze({ type: 'I', rotation: 0, x: 0 }),
      Object.freeze({ type: 'S', rotation: 1, x: 7 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    'IIIITTT.S.',
    '.OO.JTZZSS',
    '.OO.JJJZZS',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

const INTRO_02: PuzzleDefinition = Object.freeze({
  id: 't3r-shaft-02',
  name: '留井',
  difficulty: 2,
  targetRows: 3,
  seed: 560,
  setup: Object.freeze({
    seed: 3424573653,
    placements: Object.freeze([
      Object.freeze({ type: 'I', rotation: 0, x: 0 }),
      Object.freeze({ type: 'L', rotation: 0, x: 7 }),
      Object.freeze({ type: 'Z', rotation: 0, x: 3 }),
      Object.freeze({ type: 'T', rotation: 0, x: 0 }),
      Object.freeze({ type: 'J', rotation: 2, x: 3 }),
      Object.freeze({ type: 'S', rotation: 0, x: 7 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '.T.JJJ..SS',
    'TTTZZJ.SSL',
    'IIIIZZ.LLL',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

const INTRO_03: PuzzleDefinition = Object.freeze({
  id: 't3r-shaft-03',
  name: '托台',
  difficulty: 3,
  targetRows: 4,
  seed: 2900,
  setup: Object.freeze({
    seed: 37220,
    placements: Object.freeze([
      Object.freeze({ type: 'I', rotation: 0, x: 2 }),
      Object.freeze({ type: 'T', rotation: 2, x: 5 }),
      Object.freeze({ type: 'S', rotation: 1, x: 6 }),
      Object.freeze({ type: 'L', rotation: 3, x: 8 }),
      Object.freeze({ type: 'J', rotation: 3, x: 3 }),
      Object.freeze({ type: 'Z', rotation: 1, x: 1 }),
      Object.freeze({ type: 'O', rotation: 0, x: 5 }),
      Object.freeze({ type: 'L', rotation: 1, x: -1 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '...ZJOOSLL',
    'L.ZZJOOSSL',
    'L.ZJJTTTSL',
    'LLIIIIT...',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

const INTRO_04: PuzzleDefinition = Object.freeze({
  id: 't3r-cascade-06',
  name: '留口',
  difficulty: 4,
  targetRows: 4,
  seed: 83,
  setup: Object.freeze({
    seed: 49,
    placements: Object.freeze([
      Object.freeze({ type: 'I', rotation: 0, x: 6 }),
      Object.freeze({ type: 'L', rotation: 0, x: 1 }),
      Object.freeze({ type: 'T', rotation: 1, x: -1 }),
      Object.freeze({ type: 'J', rotation: 0, x: 7 }),
      Object.freeze({ type: 'O', rotation: 0, x: 8 }),
      Object.freeze({ type: 'Z', rotation: 1, x: 1 }),
      Object.freeze({ type: 'S', rotation: 0, x: 5 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '...Z..SSOO',
    'T.ZZ.SSJOO',
    'TTZL...JJJ',
    'TLLL..IIII',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

export const PUZZLE_V3_INTRO_DRAFTS: readonly PuzzleDefinition[] = Object.freeze([
  INTRO_01,
  INTRO_02,
  INTRO_03,
  INTRO_04,
]);
