import type { PuzzleDefinition } from './puzzles';

const INTRO_01: PuzzleDefinition = Object.freeze({
  id: 't3r-shaft-01',
  name: '补行',
  difficulty: 1,
  targetRows: 3,
  seed: 1212,
  setup: Object.freeze({
    seed: 2080886771,
    placements: Object.freeze([
      Object.freeze({ type: 'J', rotation: 0, x: 4 }),
      Object.freeze({ type: 'Z', rotation: 0, x: 6 }),
      Object.freeze({ type: 'T', rotation: 2, x: 4 }),
      Object.freeze({ type: 'O', rotation: 0, x: 1 }),
      Object.freeze({ type: 'I', rotation: 0, x: 0 }),
      Object.freeze({ type: 'S', rotation: 1, x: 7 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    'IIIITTT.S.',
    '.OO.JTZZSS',
    '.OO.JJJZZS',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

const INTRO_02: PuzzleDefinition = Object.freeze({
  id: 't3r-shaft-02',
  name: '留井',
  difficulty: 2,
  targetRows: 3,
  seed: 560,
  setup: Object.freeze({
    seed: 3424573653,
    placements: Object.freeze([
      Object.freeze({ type: 'I', rotation: 0, x: 0 }),
      Object.freeze({ type: 'L', rotation: 0, x: 7 }),
      Object.freeze({ type: 'Z', rotation: 0, x: 3 }),
      Object.freeze({ type: 'T', rotation: 0, x: 0 }),
      Object.freeze({ type: 'J', rotation: 2, x: 3 }),
      Object.freeze({ type: 'S', rotation: 0, x: 7 }),
    ]),
  }),
  boardRows: Object.freeze([
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
    '.T.JJJ..SS',
    'TTTZZJ.SSL',
    'IIIIZZ.LLL',
  ]),
  hiddenCells: Object.freeze([]),
  anchorCells: Object.freeze([]),
});

export const PUZZLE_V3_INTRO_DRAFTS: readonly PuzzleDefinition[] = Object.freeze([
  INTRO_01,
  INTRO_02,
]);
